name: Build/release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache electron binaries
        uses: actions/cache@v2
        with:
          path: '.cache/electron'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK : ${{ secrets.CSC_LINK }}
        with:
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          # Name of the optional NPM build script which is executed
          # before electron-builder (default: "build"
          build_script_name: 'build-react-nsis'
          # Arguments to pass to the electron-builder command,
          # e.g. configuration overrides
          args: --publish=always
